# Generated by Django 5.2.7 on 2025-11-04 14:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('cor', models.CharField(default='#6366f1', help_text='Formato: #RRGGBB', max_length=7, verbose_name='Cor (Hexadecimal)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Assinatura')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('moeda', models.CharField(default='BRL', max_length=3, verbose_name='Moeda')),
                ('ciclo_pagamento', models.CharField(choices=[('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=20, verbose_name='Ciclo de Pagamento')),
                ('data_primeira_cobranca', models.DateField(verbose_name='Data da Primeira Cobrança')),
                ('data_proxima_cobranca', models.DateField(verbose_name='Data da Próxima Cobrança')),
                ('dia_vencimento', models.IntegerField(blank=True, help_text='Dia do mês em que ocorre a cobrança (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Dia do Vencimento')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('PAUSADA', 'Pausada'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas', to='assinaturas.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['usuario', 'nome'], name='assinaturas_usuario_0a4aba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('usuario', 'nome')},
        ),
        migrations.AddIndex(
            model_name='assinatura',
            index=models.Index(fields=['usuario', 'status'], name='assinaturas_usuario_39165e_idx'),
        ),
        migrations.AddIndex(
            model_name='assinatura',
            index=models.Index(fields=['data_proxima_cobranca'], name='assinaturas_data_pr_111005_idx'),
        ),
        migrations.AddIndex(
            model_name='assinatura',
            index=models.Index(fields=['categoria'], name='assinaturas_categor_bfc288_idx'),
        ),
    ]
